2022-08-04. Отображается список афиш...
MariWinterAnne/Theatre pull request #15
Opened 2022-08-04 17:03 UTC by N1ghtStalk3r

Сделано:
1. Добавлены классы для загрузки кратких афиш.
План на завтра:
1. Надо разобраться с тем, что отображать в афишах и по каким критериям показывать.
2. Надо добавить дополнительные классы.

2022-08-15 19:08 UTC, NLCodeTeam requested changes

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/core/data/model/PosterBriefModel.kt
> +    val images: List<ModelImages>? = listOf(),
Нужно ли точно nullable?

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PosterBriefItemAdapter.kt
> +        val context: Context = holder.binding.placeImage.context
Что за конекст?

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PosterBriefItemAdapter.kt
> +        val item = data[position]
Потенциально краш, если Position выходит за границы

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +        TODO("Not yet implemented")
Добавить конкретные фрагменты

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +//class PostersListAdapter(
Удалить мусор

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PosterFragment.kt
> +
Что тут должно происходить?

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PosterListFragment.kt
> +    private fun initObservers() {
не надо добавлять пустые методы

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PostersViewModel.kt
> +//    private val getPerformanceUseCase: GetPerformanceUseCase
Убрать

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PostersViewModel.kt
> +//                getPerformanceUseCase.getPerformance().map { it.toPosterBriefItem() })
Надо убрать

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PostersViewModel.kt
> +                getPosterUseCase.getPosters()
Если в getPosters() будет exception? что произойдет?

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/network/net/PosterApi.kt
> +            events/?fields=$ID,$TITLE,$DESCRIPTION,$IMAGES&categories=theater&order_by=-publication_date&page_size=10
все вот это - categories=theater&order_by=-publication_date&page_size=10
это фильтры - они устанавливаются на уровне UI, либо дефолтные - лучше всего в UseCase
И они передаются как параметр

2022-08-15 19:08 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/core/data/mappers/MapperExt.kt
> +import com.example.theatre.core.data.model.*
star imports - настраивается в Android Studio

2022-08-16 07:41 UTC, N1ghtStalk3r commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PosterBriefItemAdapter.kt
> +        val context: Context = holder.binding.placeImage.context
Это контекст для Glide

2022-09-02 12:54 UTC, NLCodeTeam approved these changes

2022-09-02 12:54 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/core/data/model/PosterBriefModel.kt
> +    val images: List<ModelImages>?,
val images: List<ModelImages> = listOf()

2022-09-02 12:54 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/data/model/PosterDetailsModel.kt
> +    val images: List<Images>?,
лучше обезопасить себя и объявлять non nullable типы с дефолтными значениями

2022-09-02 12:54 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PosterFragment.kt
> +        viewModel.getPosterDetails(24570)
что это за цифра?

2022-09-03 05:57 UTC, merged