Исправления и добавления
MariWinterAnne/Theatre pull request #18
Opened 2023-01-26 16:45 UTC by N1ghtStalk3r

2023-02-02 08:44 UTC, eduard-amshokov requested changes

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/favourite/domain/usecase/FavouritesUseCase.kt
> +//        safeCall {
Этот код нужен тут?

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/person/PersonDescriptionFragment.kt
> +
Нуджно добавить обработчик сюда, или отметить комментарием почему должно быть пусто

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/person/PersonReviewFragment.kt
> +
так же

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/person/PersonFragment.kt
> +
аналогично предыдущему

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/theatre/TheatreDescriptionFragment.kt
> +
так же

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/theatre/TheatreDetailViewModel.kt
> +//        }
Если код не нужен, удали. Его можно восстановить из git history

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/detail/theatre/TheatreFragment.kt
> +//        is TheatreLocation -> setCity(content)
эта строка нужна?

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/info/presentation/ui/list/person/PersonsListFragment.kt
> +//    }
Либо отметь комментом для чего это закомментировано либо убери этот код

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/spectacles/presentation/ui/detail/SpectacleDetailsDescriptionFragment.kt
> +
пустой обработчик. Добавь реализацию или коммент почему должно быть пустым

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/spectacles/presentation/ui/detail/SpectacleDetailsViewModel.kt
> +
Либо добавь коммент почему ээтот код нельзя удалить, либо удали этот код

2023-02-02 08:44 UTC, eduard-amshokov commented on app/src/main/java/com/example/theatre/features/spectacles/presentation/ui/detail/SpectacleReviewFragment.kt
> +
пустой обработчик

2023-02-04 15:34 UTC, eduard-amshokov approved these changes

2023-02-04 15:35 UTC, eamshokov approved these changes

2023-02-04 18:38 UTC, merged