Файлы для фичи постера (афиши)
MariWinterAnne/Theatre pull request #4
Opened 2022-05-29 17:13 UTC by N1ghtStalk3r

В данном пулл реквесте есть файлы по фиче постера (афишиw#2r#numb2

2022-06-15 16:28 UTC, NLCodeTeam requested changes

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +            textName.text = spectacles[position].title!!.replaceFirstChar { it.uppercaseChar() }
!! - не используется никогда в коде ,если только это не наследники View, грамотно обработай ситуацию

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                textPrice.text = "бесплатно"
Откуда тут взялся этот текст? С чего ты решил, что можно прям в коде строки хардкодить ?

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                .load(spectacles[position].images[0].image.toString())
вместо images[0] можно юзать .first()

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +            textDescription.text = HtmlCompat.fromHtml(
Нарушен принцип SR, с чего вдруг адаптер стал форматтером?

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                spectacles[position].description!!,
Опять !!

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                onItemClicked(spectacles[position].id!!)
И еще !! - нам же можно упасть и закрашить приложение, если каких-то данных нет, правильно ?

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +//    lifecycle: Lifecycle,
Зачем мусорить в проекте ? убирай строчку

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +//) : FragmentStateAdapter(fm, lifecycle) {
Тоже самое

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +//    override fun getItemCount(): Int = items.size
Опять мусор

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +    private val items = arrayOf("Информация", "Детали")
Закидывай названия фрагментов в конструктор, хардкодить строки нельзя !

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +override fun getItem(position: Int): Fragment {
Тут мусора больше чем кода

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/PostersViewModel.kt
> +                _posterLoaded.value = getPerformanceUseCase.getPerformance()
На каком потоке будет выполняться - getPerformanceUseCase.getPerformance() ?

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/detail/PosterDescriptionFragment.kt
> +private const val ARG_PARAM1 = "param1"
Не надо оставлять от BlankFragmenta запчасти, добавляй пустые фрагменты, а потом доделывай их, эти аргументы тут не нужны

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/detail/PosterDetailFragment.kt
> +    private var param1: String? = null
Тоже самое, пустой фрагмент

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/detail/PosterFragment.kt
> +        viewPager.adapter = SectionPagerAdapter(requireActivity().supportFragmentManager, 0)
Что значит 0 ? вынести в const

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/list/PosterListFragment.kt
> +private const val ARG_PARAM1 = "param1"
Та же самая тема

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/res/layout/fragment_poster.xml
> +        <androidx.viewpager.widget.ViewPager
Можно сделать с ViewPager2, я сам прямо сейчас именно с ним делаю табы

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/res/layout/fragment_poster_description.xml
> +            <WebView
Зачем тут WebView ?

2022-06-15 16:28 UTC, NLCodeTeam commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Убрать это отсюда

2022-07-04 19:44 UTC, NLCodeTeam requested changes

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
>              if (spectacles[position].is_free == true) {
textPrice.text = if (spectacles[position].is_free == true)  PosterConstants.FREE else spectacles[position].price

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                .load(spectacles[position].images.first().image.toString())
А если Images будет пустым ?

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                onItemClicked(spectacles[position].id!!)
Где решение этой проблемы ?

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                onItemClicked(spectacles[position].id!!)
Где решение этой проблемы?

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +    private val items = arrayOf("Информация", "Детали")
![image](https://user-images.githubusercontent.com/24715320/177209405-82cff710-412d-421a-a513-854e6d54722d.png)

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/ui/PostersViewModel.kt
> +                _posterLoaded.value = getPerformanceUseCase.getPerformance()
Зачем тебе вообще тут _loading и зачем Dispatchers.Main ?

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/misc/PosterConstants.kt
> +class PosterConstants {
object тогда

2022-07-04 19:44 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +            textName.text = spectacles[position].title?.replaceFirstChar { it.uppercaseChar() }
private val spectacles в конструкторе

2022-07-05 10:45 UTC, N1ghtStalk3r commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                .load(spectacles[position].images.first().image.toString())
В дата классе, который мне доступен, массив картинок указан как не nullable. В ветке Марианны тот же дата класс. Исправил, добавив проверке через if

2022-07-06 19:51 UTC, NLCodeTeam requested changes

2022-07-06 19:51 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +                val pic = poster.images.first().image.toString()
Писал Марианне, что так не делается, посмотри ее МР

2022-07-06 19:51 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +        private const val POSTER_DESCRIPTION = 0
Названия и теги привяжите к фрагментам

2022-07-07 09:07 UTC, NLCodeTeam approved these changes

2022-07-07 09:07 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +//                textDescription.text = (description.orEmpty()).deleteHTML()
Мусор убрать

2022-07-07 09:07 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/PostersListAdapter.kt
> +//                String.EMPTY в core пакете. Применю после merge
core функции вам надо было выставить сразу вперед, это и есть опыт

2022-07-07 09:07 UTC, NLCodeTeam commented on app/src/main/java/com/example/theatre/features/poster/presentation/adapters/SectionPagerAdapter.kt
> +        private const val DESCRIPTION_TAB = 0
PosterDescriptionFragment {

companion object {
  const val NAME = "..."
 const val TAB_POSITION = 0
}
}

2022-07-07 11:44 UTC, merged